# Generated by Django 4.2.4 on 2023-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.TextField(blank=True),
        ),
    ]
