# Generated by Django 4.2.4 on 2023-08-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank',
        ),
    ]
