# Generated by Django 4.2.4 on 2023-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_name_remove_post_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
    ]
